# Generated by Django 5.2.9 on 2026-02-09 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_jobapplications_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customcolumn',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='jobapplications',
            name='url_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customcolumn',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('date', 'Date'), ('select', 'Select')], max_length=20),
        ),
    ]
